# Generated by Django 4.2.5 on 2023-10-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
