# Generated by Django 4.2.5 on 2023-10-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='img',
            field=models.ImageField(blank=True, upload_to='menu_item_images/'),
        ),
    ]
