# Generated by Django 4.2.6 on 2023-10-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SeniorProjectApp", "0004_carausel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carausel",
            name="image",
            field=models.ImageField(upload_to="pics/%y/%d/"),
        ),
    ]
