# Generated by Django 4.2.5 on 2023-10-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0004_menuitem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
