# Generated by Django 4.2.5 on 2023-10-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0005_alter_menuitem_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='img',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
