# Generated by Django 4.2.6 on 2023-10-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SeniorProjectApp", "0007_alter_carausel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carausel",
            name="image",
            field=models.ImageField(upload_to="SeniorProjectApp/static"),
        ),
    ]
