# Generated by Django 4.2.5 on 2023-11-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0011_customer_order_menuitem_image_delete_cart_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='image',
            field=models.ImageField(upload_to='uploads/carausel/'),
        ),
    ]
