# Generated by Django 4.2.5 on 2023-11-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0011_customer_order_menuitem_image_delete_cart_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default='', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carausel',
            name='image',
            field=models.ImageField(upload_to='uploads/carausel/'),
        ),
    ]
