# Generated by Django 4.2.5 on 2023-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0011_customer_order_menuitem_image_delete_cart_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carausel',
            name='image',
            field=models.ImageField(upload_to='uploads/carausel/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
