# Generated by Django 4.2.7 on 2023-12-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0012_menuitem_description_alter_carausel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
