# Generated by Django 4.2.5 on 2023-11-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0012_menuitem_description_alter_carausel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'slug')},
        ),
    ]
