# Generated by Django 4.2.5 on 2023-11-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0012_menuitem_description_menuitem_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
