# Generated by Django 4.2.5 on 2023-11-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0012_menuitem_description_menuitem_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
