# Generated by Django 4.2.5 on 2023-11-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeniorProjectApp', '0013_menuitem_slug_alter_menuitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
    ]
